#### Code
```kotlin
package com.glassthought.sandbox

import gt.sandbox.util.output.Out
import kotlin.concurrent.thread
import kotlin.coroutines.resume
import kotlin.coroutines.suspendCoroutine

val out = Out.standard()

suspend fun main() {
  out.info("Before-1")

  suspendCoroutine<String> { continuation ->
    // This lambda function is called right before the suspension
    // takes place.
    out.infoNonSuspend(continuation.toString())
    out.infoNonSuspend("Before-2a")
    thread {
      Thread.sleep(500)

      out.infoNonSuspend("Before-2b")

      // Question: where can we catch the result that we resumed with?
      continuation.resume("Hello from suspended coroutine")
    }
  }

  out.info("After called because we resumed")
}
```

#### Command to reproduce:
```bash
gt.sandbox.checkout.commit 155537f9e5c8d89bd00e \
&& cd "${GT_SANDBOX_REPO}" \
&& cmd.run.announce "./gradlew run --quiet"
```

#### Recorded output of command:
```txt
[elapsed:   23ms][tname:main/tid:1][coroutine:unnamed] Before-1
[elapsed:   46ms][tname:main/tid:1] SafeContinuation for Continuation at com.glassthought.sandbox.MainKt.main(Main.kt:13)
[elapsed:   47ms][tname:main/tid:1] Before-2a
[elapsed:  553ms][tname:Thread-0/tid:20] Before-2b
[elapsed:  554ms][tname:Thread-0/tid:20][coroutine:unnamed] After called because we resumed
```
