#### Code
```kotlin
package com.glassthought.sandbox

import gt.sandbox.util.output.Out
import kotlin.coroutines.resumeWithException
import kotlin.coroutines.suspendCoroutine

val out = Out.standard()

class MyException(msg: String) : Throwable(msg)

suspend fun main() {
  try {
    suspendCoroutine<Unit> { cont ->
      out.infoNonSuspend("About to resumeWithException")
      cont.resumeWithException(MyException("msg-from-resumeWithException"))
    }
  } catch (e: MyException) {
    out.info("Caught! exc-msg: " + e.message)
  }
}
```

#### Command to reproduce:
```bash
gt.sandbox.checkout.commit 32ecde1f5442756e833d \
&& cd "${GT_SANDBOX_REPO}" \
&& cmd.run.announce "./gradlew run --quiet"
```

#### Recorded output of command:
```txt
[elapsed:   24ms][tname:main/tid:1] About to resumeWithException
[elapsed:   38ms][tname:main/tid:1][coroutine:unnamed] Caught! exc-msg: msg-from-resumeWithException
```
